### PR TITLE
added reference to get_notes in cm_hookup

### LINKED ISSUE #512: Add PartInfo reference to notes
Currently the "reference" field from PartInfo is not propagated to the `get_hookup` and `get_notes` functions. An optional argument to add this could be especially useful for the website.

### PR DESCRIPTION
**Pull request by david-deboer**
Adds the reference field to the get_notes method in get_hookup:  {'notes': <note>, 'ref': <reference>}

This will close #512

### CODE REVIEW

**Comment by mkolopanis** [comment]
I think this current implementation will completely break interfaces. maybe it should be an option keyword that changes the entries to be this new dict?

**Comment by david-deboer** [comment]
I agree - we don't know who else uses this.  I'll make that change.

**Review by mkolopanis — COMMENTED** [review]
This should suffice I think. Though I am actually a little confused how the `False` statement is being tested. Are there additional tests for `get_notes` that just were not edited?

**Comment by david-deboer** [comment]
There are other tests for it that didn't need updating.

**Comment by mkolopanis** [comment]
can you also please add verbiage in your top level comment for the PR that indicates it will close #512

**Comment by mkolopanis** [comment]
a little finicky, but you have to use specific phrases for github to catch on like `closes #512`. see the full list [here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). I think if you just remove the word "issue" it should be good.

**Review by mkolopanis — APPROVED** [review]
Thanks @david-deboer

**Pull request merged**
