### PR TITLE
Add 'hard_stop' and 'force' options to the correlator control interface

### PR DESCRIPTION
**Pull request by bhazelton**
Also add some explanatory inline comments to clarify how commands are actually called.

### CODE REVIEW

**Comment by mkolopanis** [comment]
These updates look good to me, looks like it may need a re-base though and a round of onsite testing?

**Comment by bhazelton** [comment]
I will rebase now, it definitely needs onsite testing!

**Comment by mkolopanis** [comment]
Now that the interface works again I think testing could happen whenever you're ready!

**Comment by mkolopanis** [comment]
All tests pass on site: 06 April 2020

I ran these commands during an observation on 06 April 2020. 
Here's the output log. Looks reasonable to me.
```
(HERA) obs@qmaster:~/src/hera_mc$ correlator_control.py  hard_stop
Traceback (most recent call last):
  File "/home/obs/anaconda/envs/HERA/bin/correlator_control.py", line 108, in <module>
    testing=args.testing)
  File "/home/obs/anaconda/envs/HERA/lib/python3.7/site-packages/hera_mc/mc_session.py", line 2814, in correlator_control_command
    + ' is not allowed. Set the force keyword '
RuntimeError: Correlator is taking data. hard_stop is not allowed. Set the force keyword to True to override this check.
(HERA) obs@qmaster:~/src/hera_mc$ correlator_control.py  hard_stop --force
2020-04-06 19:21:45,313 - hera_corr_cm.hera_corr_cm - INFO - Issuing Hard Stop command
(HERA) obs@qmaster:~/src/hera_mc$ 

```

**Comment by bhazelton** [comment]
Thanks for testing it @mkolopanis !

**Comment by plaplant** [comment]
Thanks so much @mkolopanis! The testing shows that we get the behavior I was hoping for. I'll approve these as well. Feel free to merge anytime.

**Pull request merged**
