### PR TITLE
update daemons for new environments

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Update the daemons to point at the correct environments.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Schema change (any change to the SQL tables)
- [ ] New feature without schema change (non-breaking change which adds functionality)
- [ ] Change associated with a change in redis structure
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change
- [ ] Build or continuous integration change
- [x] Other

## Checklist:

Other:
- [x] My code follows the code style of this project.
- [x] I understand the updates required onsite (detailed in the readme) and I will make those
changes when this is merged.
- [x] Unit tests pass **on site** (This is a critical check, CI can differ from site).
- [ ] I have updated the [CHANGELOG](https://github.com/HERA-Team/hera_mc/blob/main/CHANGELOG.md).

### CODE REVIEW

**Review by david-deboer — COMMENTED** [review]
It is kind of curious that in the repo the systemd files use underscores and end with 'systemd' while in /etc/systemd/system they use hyphens and end with 'service'.  Did we do this consciously?

**Comment by bhazelton** [comment]
I don't know, I inherited this setup, I think from Peter Williams.

**Comment by mkolopanis** [comment]
I would guess it is so it can't just be copy-pasta'ed?

**Review by mkolopanis — APPROVED** [review]
This all looks reasonable to me. I'll approve but hold on a merge in case @david-deboer has more to add.

**Comment by david-deboer** [comment]
No - I'm fine, just wanted to invite comments on the naming thing.  I don't really like it but nothing specific.

**Pull request merged**
