### PR TITLE
Get pam_id and fem_id into database

### PR DESCRIPTION
**Pull request by david-deboer**
This will hopefully make this more robust in terms of getting meaningful id numbers into the database.

### CODE REVIEW

**Comment by bhazelton** [comment]
Can you explain a bit of what the fix is doing? I see that you're inserting colons between sections of a list, why is that?

**Comment by david-deboer** [comment]
Previously, this assumed a very specific format of the id reported into redis in a specific way from hera_corr_f.  That underlying fundamental way has changed in hera_corr_f.  That value was converted to hex.  Now, it handles various options and instead of a hex number converts to a colon-delimited number set or other as appropriate.  This monitoring is actually currently mostly broken on the hera_corr_f side, so will further change so this new method should allow more flexibility.

**Comment by bhazelton** [comment]
Ok, thanks. So should this PR wait on more changes in hera_corr_f?

**Comment by david-deboer** [comment]
I think that this version will handle where we end up in hera_corr_f (ie I don't think that the new way there now needs to change, but overall that monitor on hera-snap-head is not working reliably).  So, I don't think it needs to wait.  Thanks!

**Comment by bhazelton** [comment]
ok. I guess this change means that IDs for the same hardware will not match before and after.

**Review by bhazelton — APPROVED** [review]
I can't tell if this code is correct because the input comes from hera_corr_f. But if it's working on site I think it is ok.

**Pull request merged**
