### PR TITLE
Add snap_feng_init_status table

### LINKED ISSUE #615: Add armed/configured snaps to mc from snap_start.log
The snap_start.log is scraped daily after hera_feng init is run and placed into redis using:
        stat = {'timestamp': datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
                'log_time_start': self.log_time_start.strftime('%Y-%m-%dT%H:%M:%S.%f'),
                'log_time_stop': self.log_time_stop.strftime('%Y-%m-%dT%H:%M:%S.%f'),
                'working': ','.join(self.working),
                'unconfig': ','.join(self.unconfig),
                'maxout': ','.join(self.maxout)}
        r.hmset('snap_log', stat)

Fields are:
   timestamp - when the data are written to redis
   log_time_start/stop - the scraper takes the latest arm entries in the log, bracketed by these times (so this is when it happened)
   working - csv list of the snap hostnames that hera_corr_f thinks work
   unconfig - ones that made it to arming, but weren't configured (so don't work)
   maxout - ones that made it all the way, but were ignored because we had too many snaps

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add a table to track the status of SNAPs after `feng init`.

## Motivation and Context

closes #615 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Schema change (any change to the SQL tables)
- [ ] New feature without schema change (non-breaking change which adds functionality)
- [x] Change associated with a change in redis structure
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change
- [ ] Build or continuous integration change
- [ ] Other

## Checklist:

Schema change:
- [x] My code follows the code style of this project.
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [x] I have created an alembic version file to produce the schema change.
- [x] I have tested looping upgrading and downgrading the alembic version and tests pass consistently.
- [x] I understand the updates required onsite (detailed in the readme) and I will make those
changes when this is merged.
- [x] I have updated the schema documentation document with my changes (under docs/mc_definition.tex)
- [x] I have added tests to cover my new feature.
- [x] Unit tests pass **on site** (This is a critical check, CI can differ from site).
- [x] I have updated the [CHANGELOG](https://github.com/HERA-Team/hera_mc/blob/main/CHANGELOG.md).

Change associated with a change in redis structure:
- [x] My code follows the code style of this project.
- [x] I have updated the redis dump in our test data to reflect the most recent structure onsite.
- [x] I understand the updates required onsite (detailed in the readme) and I will make those
changes when this is merged.
- [x] Unit tests pass **on site** (This is a critical check, CI can differ from site).
- [x] I have updated the [CHANGELOG](https://github.com/HERA-Team/hera_mc/blob/main/CHANGELOG.md).

### CODE REVIEW

**Review by david-deboer — COMMENTED** [review]
No need to change it, but FWIW, it is handy to use:
    connection_pool = redis.ConnectionPool(host='redishost', decode_responses=True)
    rsession = redis.StrictRedis(connection_pool=connection_pool, charset='utf-8')
and then you don't need all of the decodes.

**Review by david-deboer — COMMENTED** [review]
I think that the main way people will want this data is the most recent ensemble of hostnames in each of the states.  The 'most_recent' flag just returns one entry (?) and using the 'start_time' you may not know when to start.  All of the hostnames of a given state will be nearly coincident (within a second for 'working' and the exact same time for the other two states here).  It would be good to have a convenience function to return the ensemble.  Maybe we make an issue on that, because we don't want to delay when we start logging...  It might be good to assign a student to that -- we want more folks familiar with the hera_mc code base.

**Comment by bhazelton** [comment]
Since all the most recent ones have the same time stamp, asking for the most recent should get the entire set.

**Comment by bhazelton** [comment]
> No need to change it, but FWIW, it is handy to use:
> connection_pool = redis.ConnectionPool(host='redishost', decode_responses=True)
> rsession = redis.StrictRedis(connection_pool=connection_pool, charset='utf-8')
> and then you don't need all of the decodes.

Very handy, thanks!

**Review by david-deboer — APPROVED** [review]
Looks good.

**Review by dannyjacobs — APPROVED** [review]
The feng_start log distinguishes between ethernet connection timeouts and ADC cal/alignment issues. Far as I can tell, this logging does not distinguish between those two cases. But its a good start.
Don't understand the detail question about dates in selections, but it sounds like somewhere I've been before.   
SQL selection usability looks ok. Should be straightforward to make a dashboard that plots/lists failure count for each snap.

**Comment by bhazelton** [comment]
> The feng_start log distinguishes between ethernet connection timeouts and ADC cal/alignment issues

@david-deboer do you want to include this detail?

**Comment by david-deboer** [comment]
The hera_mc structure will handle using different keywords, so we can incorporate later (it would only be docstring changes).

**Comment by bhazelton** [comment]
> The hera_mc structure will handle using different keywords, so we can incorporate later (it would only be docstring changes).

Yes, as well as updates to the tex.

**Review by david-deboer — APPROVED** [review]
Ok

**Pull request merged**
