### PR TITLE
start testing against python 3

### LINKED ISSUE #229: python 3 compatibility

### PR DESCRIPTION
**Pull request by bhazelton**
disabled qm testing for python 3 until it is compatible

fixes #229

### CODE REVIEW

**Comment by bhazelton** [comment]
The python 3 test is failing with:
```conda list
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli```

Any idea what might be going on here @pkgw?

**Comment by bhazelton** [comment]
Oh! When I install all the packages it's downgrading python to 2.7

**Comment by bhazelton** [comment]
hmm, maybe because it's grabbing pyuvdata 1.2.1 not 1.3
I wonder why that's happening

**Comment by pkgw** [comment]
Try removing the `conda config --remove channels defaults &&` bit.

**Comment by bhazelton** [comment]
I think you fixed it @pkgw, thank you! Looks like something's wedged with travis/coveralls reporting, I'm going to restart the Travis build to try to fix it.

**Comment by pkgw** [comment]
I squashed the commits since I wanted to make one final tweak to get rid of the `conda search` debugging line. Coveralls is sad because our test coverage went down since Python 3 covers a smaller fraction of the code than Python 2 — by definition, since we intentionally skipped the QM tests. So, tough noogies, Coveralls.

**Pull request merged**
