### PR TITLE
Fix dishes plotted inthe past

### PR DESCRIPTION
**Pull request by dannyjacobs**
Fixes issue #281. Changes how get_location works. Now only returns dishes built prior to query_date.
I believe this is the desired behavior.

### CODE REVIEW

**Comment by bhazelton** [comment]
This might be right, but I would have thought we'd want only the fully connected antennas at the date specified (which is not the same as the dishes having been built)...

**Comment by bhazelton** [comment]
@dannyjacobs why are there 10 commits in this 2 line PR?

**Comment by dannyjacobs** [comment]
Because I had a bunch of merge commits sitting on my master branch.  Looking at the final master-branch diff, I see only one file affected.

**Comment by david-deboer** [comment]
I think we can withdraw this one for the new PR I'll put in in a few moments.

**Comment by bhazelton** [comment]
will be fixed via #284

**Pull request closed without merging**
