### PR TITLE
Viewwx

### PR DESCRIPTION
**Pull request by david-deboer**
Adds a weather Handling class, which currently gets reads the table and writes files (and then also can read those files).  A flag has been added to mc_wx.py (-W) which dumps the weather data to files.

### CODE REVIEW

**Comment by pkgw** [comment]
What's the motivation for this PR? If we're basically interested in having a way to dump the weather data to a file for diagnostics, a bunch of this code could be eliminated. I.e., nothing actually uses the `read_weather_files` function right now.

I think this is particularly important to think about since we can expect the weather tables to get quite sizeable. As written, any operations involving the `weather.Handling` class are eventually going to involve gigantic dictionaries that will be extremely slow to work with. If we don't actually need a general-purpose "all weather data from all time" data structure, we can almost surely design it to be much more efficient for whatever our actual use case is.

**Comment by david-deboer** [comment]
We want to look at weather data and this is a start.  I could write my own code to do it on my machine and Danny could write his own code to do it on his machine and ...  so I thought I'd give some basic starter functions/structure.  A logical extension is to allow frequency ranges etc etc, which I'll likely do but there was a call in HERA_Commissioning to look at weather data and this was the underlying code.

**Comment by bhazelton** [comment]
I think we need to understand the Commissioning issue a bit more. It seems very inefficient to write it to a file when it already exists in the database and there are methods to get it all out for a given time range. Are you planning to copy the files somewhere else to plot them? That seems a bit hacky and as Peter points out, the files are likely to get very big. Is it a bad idea to plot them on qmaster?

**Comment by pkgw** [comment]
Are you referring to HERA-Team/HERA_Commissioning#80? (GitHub cross-references the mentions so it's helpful to drop them in the discussions explicitly.)

**Pull request closed without merging**
