### PR TITLE
Fix compatibility with sqlalchemy2.0

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

SQLAlchemy 2.0 is out and it broke some things. This PR fixes:
- compatibility with SQLAlchemy 2.0
- Some old problems in alembic revisions that prevented upgrades and downgrades from being fully reversible.
- Adds a new CI that runs the tests with the `-W error` flag to catch warnings. As on other repos, I don't think this should be a required check, but it will prevent us missing new deprecation warnings (as we did with the changes in SQLAlchemy 2.0 which were warned about for some time apparently).
- Drop support for python 3.7.
- Fixes conftest and cm_utils.py to make it possible to run tests from another folder. Runs from another folder in the min_deps test to improve coverage in `__init__.py`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Schema change (any change to the SQL tables)
- [ ] New feature without schema change (non-breaking change which adds functionality)
- [ ] Change associated with a change in redis structure
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change
- [ ] Build or continuous integration change
- [ ] Other

## Checklist:

Bug fix checklist:
- [x] My code follows the code style of this project.
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] I understand the updates required onsite (detailed in the readme) and I will make those
changes when this is merged.
- [x] Unit tests pass **on site** (This is a critical check, CI can differ from site).
- [x] I have updated the [CHANGELOG](https://github.com/HERA-Team/hera_mc/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by mkolopanis** [comment]
do we need to force sqlalchemy version to be >=2?

**Comment by bhazelton** [comment]
This doesn't break compatibility with older versions of sqlalchemy. I am sure of this because a python 3.7 run passed using sqlalchemy 1.4.

However, after I removed `pkg_resources` in favor of `importlib.metadata`, python 3.7 is no longer passing because `importlib.metadata` was introduced in python 3.8. I'm now wondering how important it is to keep supporting python 3.7. Are we using it anywhere onsite?

**Comment by mkolopanis** [comment]
I'm not aware of anywhere on site it is used. I would argue if we have an older environment maybe we should update it. But we'll have to go check all the environments.

**Comment by bhazelton** [comment]
per a conversation on Slack, I removed support for python 3.7

**Review by mkolopanis — APPROVED** [review]
Thanks for the updates and checking on site. I think this is working for me.

**Comment by bhazelton** [comment]
I've now tested this onsite without errors, so I'm going to merge.

**Pull request merged**
